//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETIMAGE
    {
        public int ASSETIMAGEID { get; set; }
        public string ASSETID { get; set; }
        public string Filepath { get; set; }
        public int ID { get; set; }
    }
}
