//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccetManagementEntities : DbContext
    {
        public AccetManagementEntities()
            : base("name=AccetManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSET> ASSETs { get; set; }
        public virtual DbSet<ASSETIMAGE> ASSETIMAGEs { get; set; }
        public virtual DbSet<ASSETTYPE> ASSETTYPEs { get; set; }
        public virtual DbSet<ATTATCHMENT> ATTATCHMENTs { get; set; }
        public virtual DbSet<CHECKOUTIN> CHECKOUTINs { get; set; }
        public virtual DbSet<CONDITION> CONDITIONs { get; set; }
        public virtual DbSet<Depreciation> Depreciations { get; set; }
        public virtual DbSet<EMPLOYEESTATU> EMPLOYEESTATUS { get; set; }
        public virtual DbSet<EMPLOYEETABLE> EMPLOYEETABLEs { get; set; }
        public virtual DbSet<FINANCE> FINANCEs { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<ORGANIZATIONGROUP> ORGANIZATIONGROUPs { get; set; }
        public virtual DbSet<ORGANIZATIONROLE> ORGANIZATIONROLEs { get; set; }
        public virtual DbSet<SERVICETABLE> SERVICETABLEs { get; set; }
        public virtual DbSet<SERVICETYPE> SERVICETYPEs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
        public virtual DbSet<RPTALLASSET> RPTALLASSETS { get; set; }
        public virtual DbSet<RPTASSIGNEDALLASSET> RPTASSIGNEDALLASSETS { get; set; }
        public virtual DbSet<RPTUNASSIGNEDALLASSET> RPTUNASSIGNEDALLASSETS { get; set; }
        public virtual DbSet<VIEWALLASSET> VIEWALLASSETS { get; set; }
        public virtual DbSet<VIEWALLEMP> VIEWALLEMPs { get; set; }
        public virtual DbSet<VIEWCHECKOUT> VIEWCHECKOUTs { get; set; }
        public virtual DbSet<VIEWCHECKOUTsearch> VIEWCHECKOUTsearches { get; set; }
        public virtual DbSet<VIEWEMPCHECKOUTLIST> VIEWEMPCHECKOUTLISTs { get; set; }
        public virtual DbSet<RPTVIEWALLEMP> RPTVIEWALLEMPs { get; set; }
        public virtual DbSet<EMPLOYEEIMAGE> EMPLOYEEIMAGEs { get; set; }
    }
}
