//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET
    {
        public string ASSETNO { get; set; }
        public string DESCRIPTION { get; set; }
        public int ASSETTYPEID { get; set; }
        public int LOCATIONID { get; set; }
        public string MANUFACTURER { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string SERIALNUMBER { get; set; }
        public int STATUSID { get; set; }
        public int CONDITIONID { get; set; }
        public string EMPNAME { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string NOTES { get; set; }
        public int ASSETIMAGEID { get; set; }
        public System.DateTime CHECKOUTDATE { get; set; }
        public string CHECKOUTCOMMENT { get; set; }
        public string EMPID { get; set; }
        public System.DateTime RECEIVEDDATE { get; set; }
        public int ID { get; set; }
    }
}
