//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEETABLE
    {
        public int ID { get; set; }
        public string EMPID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string WORKPHONE { get; set; }
        public string MOBILEPHONE { get; set; }
        public string EMAIL { get; set; }
        public int STATUSID { get; set; }
        public int GROUPID { get; set; }
        public int TITLEID { get; set; }
        public int IMAGEID { get; set; }
    }
}
