//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE
    {
        public string VENDORNO { get; set; }
        public string PONO { get; set; }
        public int RECOVERYPERIOD { get; set; }
        public decimal PURCHASEPRICE { get; set; }
        public decimal MARKETVALUE { get; set; }
        public decimal SCRAPEVALUE { get; set; }
        public int DEPRECIATIONID { get; set; }
        public System.DateTime PURCHASEDATE { get; set; }
        public System.DateTime INSERVICEDATE { get; set; }
        public System.DateTime WARRANTYEND { get; set; }
        public string ASSETNO { get; set; }
        public int ID { get; set; }
    }
}
