//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTALLASSET
    {
        public string ASSETTYPE { get; set; }
        public string STATUSNAME { get; set; }
        public string LOCATIONNAME { get; set; }
        public string CONDITIONNAME { get; set; }
        public string ASSETNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string MANUFACTURER { get; set; }
        public string BRAND { get; set; }
        public string SERIALNUMBER { get; set; }
        public string EMPNAME { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string NOTES { get; set; }
    }
}
