//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICETYPE
    {
        public string SERVICENAME { get; set; }
        public int SERVICETYPEID { get; set; }
    }
}
