//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICETABLE
    {
        public int ID { get; set; }
        public string ASSETNO { get; set; }
        public decimal LABORCOST { get; set; }
        public decimal PARTSCOST { get; set; }
        public decimal TAX { get; set; }
        public System.DateTime COMPLETIONDATE { get; set; }
        public System.DateTime NEXTDUEDATE { get; set; }
        public string SERVICEDBY { get; set; }
        public int SERVICETYPEID { get; set; }
    }
}
