//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public string VENDORNAME { get; set; }
        public string VENDORNO { get; set; }
        public string PHONENO { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public string CONTACTNAME { get; set; }
        public string POSTALADDRESS { get; set; }
        public string TOWN { get; set; }
        public string COUNTRY { get; set; }
    }
}
