//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWCHECKOUT
    {
        public string DESCRIPTION { get; set; }
        public string ASSETNO { get; set; }
        public string ADDITIONALINFORMATION { get; set; }
        public string FULLDESCRIPTION { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public string COMPUTERNAME { get; set; }
        public string PERSONALNO { get; set; }
    }
}
