//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWEMPCHECKOUTLIST
    {
        public string ASSETNO { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CHECKOUTDATE { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string EMPID { get; set; }
    }
}
