//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWALLEMP
    {
        public string EMPID { get; set; }
        public string EMAIL { get; set; }
        public string MOBILEPHONE { get; set; }
        public string TITLE { get; set; }
        public string EMPSTATUSNAME { get; set; }
        public int ID { get; set; }
        public string EMPNAME { get; set; }
    }
}
